image:
  repository: host.docker.internal:30003/library/hello-world
  tag: "1.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-creds

service:
  type: NodePort
  port: 80

replicaCount: 1

